/* $Id: public.h,v 1.1 2005/05/15 07:06:33 ecd Exp $
 *
 * DO NOT EDIT, automatically generated by 'keygen'.
 */

#ifndef _PUBLIC_H
#define _PUBLIC_H 1

extern const char *rsa_n;
extern const char *rsa_e;

#endif /* !(_PUBLIC_H) */
